DROP TABLE PARTICIPARI_COMPETITIE CASCADE CONSTRAINTS;
DROP TABLE ORAR_TEMPLATE CASCADE CONSTRAINTS;
DROP TABLE NECESAR_ECHIPAMENT CASCADE CONSTRAINTS;
DROP TABLE MENTORAT CASCADE CONSTRAINTS;
DROP TABLE INSCRIERI CASCADE CONSTRAINTS;
DROP TABLE ACHIZITII CASCADE CONSTRAINTS;
DROP TABLE CLASE CASCADE CONSTRAINTS;
DROP TABLE MEMBRI CASCADE CONSTRAINTS;
DROP TABLE COMPETITII CASCADE CONSTRAINTS;
DROP TABLE TIPURI_ANTRENAMENT CASCADE CONSTRAINTS;
DROP TABLE ECHIPAMENTE CASCADE CONSTRAINTS;
DROP TABLE PRODUSE CASCADE CONSTRAINTS;
DROP TABLE ANTRENORI CASCADE CONSTRAINTS;
DROP TABLE ABONAMENTE CASCADE CONSTRAINTS;

DROP SEQUENCE MEMBRI_SEQ;
DROP SEQUENCE ABONAMENTE_SEQ;
DROP SEQUENCE ANTRENORI_SEQ;
DROP SEQUENCE CLASE_SEQ;
DROP SEQUENCE PRODUSE_SEQ;
DROP SEQUENCE ECHIPAMENTE_SEQ;
DROP SEQUENCE TIPURI_ANTRENAMENT_SEQ;
DROP SEQUENCE ACHIZITII_SEQ;
DROP SEQUENCE ORAR_TEMPLATE_SEQ;
DROP SEQUENCE COMPETITII_SEQ;

CREATE SEQUENCE MEMBRI_SEQ NOCACHE;
CREATE SEQUENCE ABONAMENTE_SEQ NOCACHE;
CREATE SEQUENCE ANTRENORI_SEQ NOCACHE;
CREATE SEQUENCE CLASE_SEQ NOCACHE;
CREATE SEQUENCE PRODUSE_SEQ NOCACHE;
CREATE SEQUENCE ECHIPAMENTE_SEQ NOCACHE;
CREATE SEQUENCE TIPURI_ANTRENAMENT_SEQ NOCACHE;
CREATE SEQUENCE ACHIZITII_SEQ NOCACHE;
CREATE SEQUENCE ORAR_TEMPLATE_SEQ NOCACHE;
CREATE SEQUENCE COMPETITII_SEQ NOCACHE;

CREATE TABLE ABONAMENTE (
    ABONAMENTID  NUMBER(10) PRIMARY KEY,
    TIPABONAMENT VARCHAR2(100) NOT NULL,
    PRET         NUMBER(10, 2) NOT NULL,
    CONSTRAINT CHK_ABONAMENT_PRET CHECK (PRET >= 0)
);

CREATE TABLE ANTRENORI (
    ANTRENORID   NUMBER(10) PRIMARY KEY,
    NUME         VARCHAR2(100) NOT NULL,
    PRENUME      VARCHAR2(100),
    SPECIALIZARE VARCHAR2(150),
    CONSTRAINT CHK_SPECIALIZARE CHECK (SPECIALIZARE IN ('Gimnastica', 'Haltere', 'Crossfit L1', 'Crossfit L2', 'Mobilitate', 'Cardio'))
);

CREATE TABLE PRODUSE (
    PRODUSID   NUMBER(10) PRIMARY KEY,
    NUMEPRODUS VARCHAR2(150) NOT NULL,
    PRETCURENT NUMBER(10, 2),
    STOC       NUMBER(5),
    CONSTRAINT CHK_PRODUS_PRET CHECK (PRETCURENT >= 0),
    CONSTRAINT CHK_PRODUS_STOC CHECK (STOC >= 0)
);

CREATE TABLE ECHIPAMENTE (
    ECHIPAMENTID    NUMBER(10) PRIMARY KEY,
    NUMEECHIPAMENT  VARCHAR2(100) NOT NULL,
    CANTITATETOTALA NUMBER(5),
    CONSTRAINT CHK_ECHIPAMENT_CANT CHECK (CANTITATETOTALA >= 0)
);

CREATE TABLE TIPURI_ANTRENAMENT (
    TIPANTRENAMENTID NUMBER(10) PRIMARY KEY,
    NUMEWOD          VARCHAR2(100) NOT NULL,
    DESCRIERE        VARCHAR2(1000)
);

CREATE TABLE COMPETITII (
    COMPETITIEID NUMBER(10) PRIMARY KEY,
    NUME         VARCHAR2(150) NOT NULL,
    DATA         DATE NOT NULL,
    LOCATIE      VARCHAR2(150),
    TAXA         NUMBER(10, 2) DEFAULT 0,
    CONSTRAINT CHK_COMPETITIE_TAXA CHECK (TAXA >= 0)
);

CREATE TABLE MEMBRI (
    MEMBRUID    NUMBER(10) PRIMARY KEY,
    NUME        VARCHAR2(100) NOT NULL,
    PRENUME     VARCHAR2(100),
    EMAIL       VARCHAR2(150) NOT NULL UNIQUE,
    ABONAMENTID NUMBER(10),
    CONSTRAINT CHK_MEMBRU_EMAIL CHECK (EMAIL LIKE '%@%'),
    CONSTRAINT FK_MEMBRI_ABONAMENT FOREIGN KEY (ABONAMENTID) REFERENCES ABONAMENTE(ABONAMENTID)
);

CREATE TABLE CLASE (
    CLASAID          NUMBER(10) PRIMARY KEY,
    NUMEWOD          VARCHAR2(100) NOT NULL,
    DESCRIEREWOD     VARCHAR2(1000),
    DATAORA          TIMESTAMP(6),
    ANTRENORID       NUMBER(10),
    TIPANTRENAMENTID NUMBER(10),
    CONSTRAINT FK_CLASE_ANTRENOR FOREIGN KEY (ANTRENORID) REFERENCES ANTRENORI(ANTRENORID),
    CONSTRAINT FK_CLASE_TIP FOREIGN KEY (TIPANTRENAMENTID) REFERENCES TIPURI_ANTRENAMENT(TIPANTRENAMENTID)
);

CREATE TABLE ACHIZITII (
    ACHIZITIEID    NUMBER(10) PRIMARY KEY,
    MEMBRUID       NUMBER(10),
    PRODUSID       NUMBER(10),
    DATAACHIZITIEI DATE DEFAULT SYSDATE,
    CANTITATE      NUMBER(3) DEFAULT 1,
    CONSTRAINT FK_ACHIZITII_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE,
    CONSTRAINT FK_ACHIZITII_PRODUS FOREIGN KEY (PRODUSID) REFERENCES PRODUSE(PRODUSID),
    CONSTRAINT CHK_ACHIZITIE_CANT CHECK (CANTITATE > 0)
);

CREATE TABLE INSCRIERI (
    MEMBRUID NUMBER(10) NOT NULL,
    CLASAID  NUMBER(10) NOT NULL,
    CONSTRAINT PK_INSCRIERI PRIMARY KEY (MEMBRUID, CLASAID),
    CONSTRAINT FK_INSCRIERI_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE,
    CONSTRAINT FK_INSCRIERI_CLASA FOREIGN KEY (CLASAID) REFERENCES CLASE(CLASAID) ON DELETE CASCADE
);

CREATE TABLE MENTORAT (
    ANTRENORID NUMBER(10) NOT NULL,
    MEMBRUID   NUMBER(10) NOT NULL,
    CONSTRAINT PK_MENTORAT PRIMARY KEY (ANTRENORID, MEMBRUID),
    CONSTRAINT FK_MENTORAT_ANTRENOR FOREIGN KEY (ANTRENORID) REFERENCES ANTRENORI(ANTRENORID),
    CONSTRAINT FK_MENTORAT_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE
);

CREATE TABLE NECESAR_ECHIPAMENT (
    TIPANTRENAMENTID NUMBER(10) NOT NULL,
    ECHIPAMENTID     NUMBER(10) NOT NULL,
    CONSTRAINT PK_NECESAR_ECHIPAMENT PRIMARY KEY (TIPANTRENAMENTID, ECHIPAMENTID),
    CONSTRAINT FK_NECESAR_TIP FOREIGN KEY (TIPANTRENAMENTID) REFERENCES TIPURI_ANTRENAMENT(TIPANTRENAMENTID) ON DELETE CASCADE,
    CONSTRAINT FK_NECESAR_ECHIPAMENT FOREIGN KEY (ECHIPAMENTID) REFERENCES ECHIPAMENTE(ECHIPAMENTID) ON DELETE CASCADE
);

CREATE TABLE ORAR_TEMPLATE (
    TEMPLATEID       NUMBER(10) PRIMARY KEY,
    ZIUASAPTAMANII   NUMBER(1) NOT NULL,
    ORA              VARCHAR2(5) NOT NULL,
    NUMEWOD_TEMPLATE VARCHAR2(100),
    ANTRENORID       NUMBER(10),
    TIPANTRENAMENTID NUMBER(10),
    CONSTRAINT CHK_ZIUA_SAPTAMANII CHECK (ZIUASAPTAMANII BETWEEN 1 AND 7),
    CONSTRAINT CHK_ORA_FORMAT CHECK (REGEXP_LIKE(ORA, '^[0-2][0-9]:[0-5][0-9]$')),
    CONSTRAINT FK_ORAR_ANTRENOR FOREIGN KEY (ANTRENORID) REFERENCES ANTRENORI(ANTRENORID) ON DELETE SET NULL,
    CONSTRAINT FK_ORAR_TIP FOREIGN KEY (TIPANTRENAMENTID) REFERENCES TIPURI_ANTRENAMENT(TIPANTRENAMENTID) ON DELETE SET NULL
);

CREATE TABLE PARTICIPARI_COMPETITIE (
    COMPETITIEID NUMBER(10) NOT NULL,
    MEMBRUID     NUMBER(10) NOT NULL,
    LOCULOBTINUT NUMBER(3) DEFAULT 0,
    CONSTRAINT PK_PARTICIPARI_COMP PRIMARY KEY (COMPETITIEID, MEMBRUID),
    CONSTRAINT FK_PART_COMP FOREIGN KEY (COMPETITIEID) REFERENCES COMPETITII(COMPETITIEID) ON DELETE CASCADE,
    CONSTRAINT FK_PART_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE
);

CREATE OR REPLACE VIEW V_ANTRENORI_CONTACT AS
SELECT AntrenorID, Nume, Prenume, Specializare
FROM ANTRENORI;

CREATE OR REPLACE VIEW V_MEMBRI_ABONAMENTE AS
SELECT m.Nume, m.Prenume, m.Email, a.TipAbonament, a.Pret
FROM MEMBRI m
JOIN ABONAMENTE a ON m.AbonamentID = a.AbonamentID;

CREATE OR REPLACE VIEW V_RAPORT_POPULARITATE AS
SELECT a.TipAbonament, COUNT(m.MembruID) AS Numar_Membri
FROM ABONAMENTE a
JOIN MEMBRI m ON a.AbonamentID = m.AbonamentID
GROUP BY a.TipAbonament
HAVING COUNT(m.MembruID) > 2;

COMMIT;
