
DROP TABLE PARTICIPARI_COMPETITIE CASCADE CONSTRAINTS;
DROP TABLE NECESAR_ECHIPAMENT CASCADE CONSTRAINTS;
DROP TABLE MENTORAT CASCADE CONSTRAINTS;
DROP TABLE INSCRIERI CASCADE CONSTRAINTS;
DROP TABLE ACHIZITII CASCADE CONSTRAINTS;
DROP TABLE CLASE CASCADE CONSTRAINTS;
DROP TABLE MEMBRI CASCADE CONSTRAINTS;
DROP TABLE COMPETITII CASCADE CONSTRAINTS;
DROP TABLE TIPURI_ANTRENAMENT CASCADE CONSTRAINTS;
DROP TABLE ECHIPAMENTE CASCADE CONSTRAINTS;
DROP TABLE PRODUSE CASCADE CONSTRAINTS;
DROP TABLE ANTRENORI CASCADE CONSTRAINTS;
DROP TABLE ABONAMENTE CASCADE CONSTRAINTS;

DROP SEQUENCE MEMBRI_SEQ;
DROP SEQUENCE ABONAMENTE_SEQ;
DROP SEQUENCE ANTRENORI_SEQ;
DROP SEQUENCE CLASE_SEQ;
DROP SEQUENCE PRODUSE_SEQ;
DROP SEQUENCE ECHIPAMENTE_SEQ;
DROP SEQUENCE TIPURI_ANTRENAMENT_SEQ;
DROP SEQUENCE ACHIZITII_SEQ;
DROP SEQUENCE COMPETITII_SEQ;

CREATE SEQUENCE MEMBRI_SEQ NOCACHE;
CREATE SEQUENCE ABONAMENTE_SEQ NOCACHE;
CREATE SEQUENCE ANTRENORI_SEQ NOCACHE;
CREATE SEQUENCE CLASE_SEQ NOCACHE;
CREATE SEQUENCE PRODUSE_SEQ NOCACHE;
CREATE SEQUENCE ECHIPAMENTE_SEQ NOCACHE;
CREATE SEQUENCE TIPURI_ANTRENAMENT_SEQ NOCACHE;
CREATE SEQUENCE ACHIZITII_SEQ NOCACHE;
CREATE SEQUENCE COMPETITII_SEQ NOCACHE;

CREATE TABLE ABONAMENTE (
    AbonamentID  NUMBER(10) PRIMARY KEY,
    TipAbonament VARCHAR2(100) NOT NULL,
    Pret         NUMBER(10, 2) NOT NULL CHECK (Pret > 0)
);

CREATE TABLE ANTRENORI (
    AntrenorID   NUMBER(10) PRIMARY KEY,
    Nume         VARCHAR2(50) NOT NULL,
    Prenume      VARCHAR2(50) NOT NULL,
    Specializare VARCHAR2(100)
);

CREATE TABLE MEMBRI (
    MembruID    NUMBER(10) PRIMARY KEY,
    Nume        VARCHAR2(50) NOT NULL,
    Prenume     VARCHAR2(50) NOT NULL,
    Email       VARCHAR2(100) UNIQUE,
    AbonamentID NUMBER(10) NOT NULL,
    CONSTRAINT FK_MEMBRI_ABONAMENT FOREIGN KEY (AbonamentID) REFERENCES ABONAMENTE(AbonamentID) ON DELETE CASCADE
);

CREATE TABLE MENTORAT (
    AntrenorID NUMBER(10) NOT NULL,
    MembruID   NUMBER(10) NOT NULL,
    CONSTRAINT PK_MENTORAT PRIMARY KEY (AntrenorID, MembruID),
    CONSTRAINT FK_MENTORAT_ANTRENOR FOREIGN KEY (AntrenorID) REFERENCES ANTRENORI(AntrenorID) ON DELETE CASCADE,
    CONSTRAINT FK_MENTORAT_MEMBRU FOREIGN KEY (MembruID) REFERENCES MEMBRI(MembruID) ON DELETE CASCADE
);

CREATE TABLE TIPURI_ANTRENAMENT (
    TipID       NUMBER(10) PRIMARY KEY,
    NumeWOD     VARCHAR2(100) NOT NULL,
    Descriere   VARCHAR2(1000)
);

CREATE TABLE CLASE (
    ClasaID    NUMBER(10) PRIMARY KEY,
    AntrenorID NUMBER(10) NOT NULL,
    TipID      NUMBER(10) NOT NULL,
    DataOra    DATE NOT NULL,
    CONSTRAINT FK_CLASE_ANTRENOR FOREIGN KEY (AntrenorID) REFERENCES ANTRENORI(AntrenorID) ON DELETE CASCADE,
    CONSTRAINT FK_CLASE_TIP FOREIGN KEY (TipID) REFERENCES TIPURI_ANTRENAMENT(TipID) ON DELETE CASCADE
);

CREATE TABLE INSCRIERI (
    MembruID NUMBER(10) NOT NULL,
    ClasaID  NUMBER(10) NOT NULL,
    CONSTRAINT PK_INSCRIERI PRIMARY KEY (MembruID, ClasaID),
    CONSTRAINT FK_INSCRIERI_MEMBRU FOREIGN KEY (MembruID) REFERENCES MEMBRI(MembruID) ON DELETE CASCADE,
    CONSTRAINT FK_INSCRIERI_CLASA FOREIGN KEY (ClasaID) REFERENCES CLASE(ClasaID) ON DELETE CASCADE
);

CREATE TABLE COMPETITII (
    CompetitieID NUMBER(10) PRIMARY KEY,
    Nume         VARCHAR2(100) NOT NULL,
    Data         DATE NOT NULL,
    Taxa         NUMBER(10, 2) DEFAULT 0
);

CREATE TABLE PARTICIPARI_COMPETITIE (
    CompetitieID NUMBER(10) NOT NULL,
    MembruID     NUMBER(10) NOT NULL,
    LoculObtinut NUMBER(3) DEFAULT 0,
    CONSTRAINT PK_PARTICIPARI_COMP PRIMARY KEY (CompetitieID, MembruID),
    CONSTRAINT FK_PART_COMP FOREIGN KEY (CompetitieID) REFERENCES COMPETITII(CompetitieID) ON DELETE CASCADE,
    CONSTRAINT FK_PART_MEMBRU FOREIGN KEY (MembruID) REFERENCES MEMBRI(MembruID) ON DELETE CASCADE
);

CREATE TABLE ECHIPAMENTE (
    EchipamentID     NUMBER(10) PRIMARY KEY,
    NumeEchipament   VARCHAR2(100) NOT NULL,
    CantitateTotala  NUMBER(5) CHECK (CantitateTotala >= 0)
);

CREATE TABLE NECESAR_ECHIPAMENT (
    TipID        NUMBER(10) NOT NULL,
    EchipamentID NUMBER(10) NOT NULL,
    CONSTRAINT PK_NECESAR_ECHIPAMENT PRIMARY KEY (TipID, EchipamentID),
    CONSTRAINT FK_NECESAR_TIP FOREIGN KEY (TipID) REFERENCES TIPURI_ANTRENAMENT(TipID) ON DELETE CASCADE,
    CONSTRAINT FK_NECESAR_ECHIPAMENT FOREIGN KEY (EchipamentID) REFERENCES ECHIPAMENTE(EchipamentID) ON DELETE CASCADE
);

CREATE TABLE PRODUSE (
    ProdusID   NUMBER(10) PRIMARY KEY,
    NumeProdus VARCHAR2(100) NOT NULL,
    PretCurent NUMBER(10, 2) NOT NULL,
    Stoc       NUMBER(5) DEFAULT 0
);

CREATE TABLE ACHIZITII (
    AchizitieID NUMBER(10) PRIMARY KEY,
    MembruID    NUMBER(10) NOT NULL,
    ProdusID    NUMBER(10) NOT NULL,
    Data        DATE DEFAULT SYSDATE,
    Cantitate   NUMBER(5) CHECK (Cantitate > 0),
    CONSTRAINT FK_ACHIZITII_MEMBRU FOREIGN KEY (MembruID) REFERENCES MEMBRI(MembruID) ON DELETE CASCADE,
    CONSTRAINT FK_ACHIZITII_PRODUS FOREIGN KEY (ProdusID) REFERENCES PRODUSE(ProdusID) ON DELETE CASCADE
);
COMMIT;
