INSERT INTO CROSSFIT_ADMIN.ABONAMENTE (ABONAMENTID, TIPABONAMENT, PRET) VALUES (1, 'Nelimitat 1 Luna', 250.00);
INSERT INTO CROSSFIT_ADMIN.ABONAMENTE (ABONAMENTID, TIPABONAMENT, PRET) VALUES (2, '10 Sedinte', 200.00);
INSERT INTO CROSSFIT_ADMIN.ABONAMENTE (ABONAMENTID, TIPABONAMENT, PRET) VALUES (3, 'Nelimitat 6 Luni', 1300.00);
INSERT INTO CROSSFIT_ADMIN.ABONAMENTE (ABONAMENTID, TIPABONAMENT, PRET) VALUES (4, '12 Sedinte', 220.00);
INSERT INTO CROSSFIT_ADMIN.ABONAMENTE (ABONAMENTID, TIPABONAMENT, PRET) VALUES (5, '8 Sedinte', 180.00);
INSERT INTO CROSSFIT_ADMIN.ABONAMENTE (ABONAMENTID, TIPABONAMENT, PRET) VALUES (6, '4 Sedinte', 100.00);
