INSERT INTO CROSSFIT_ADMIN.ANTRENORI (ANTRENORID, NUME, PRENUME, SPECIALIZARE) VALUES (101, 'Popescu', 'Andrei', 'Haltere');
INSERT INTO CROSSFIT_ADMIN.ANTRENORI (ANTRENORID, NUME, PRENUME, SPECIALIZARE) VALUES (102, 'Marinescu', 'Ioana', 'Gimnastică');
