INSERT INTO CROSSFIT_ADMIN.ECHIPAMENTE (ECHIPAMENTID, NUMEECHIPAMENT, CANTITATETOTALA) VALUES (301, 'Kettlebell 16kg', 20);
INSERT INTO CROSSFIT_ADMIN.ECHIPAMENTE (ECHIPAMENTID, NUMEECHIPAMENT, CANTITATETOTALA) VALUES (302, 'Coarda de sarit', 40);
