INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (207, 'Băutură pre-antrenament', 10.00, 100);
INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (201, 'Baton Proteic Ciocolata', 10.00, 50);
INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (202, 'Apa Plata 0.5L', 3.00, 100);
INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (203, 'Băutură energizantă', 8.00, 40);
INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (204, 'Shaker CrossFit', 35.00, 15);
INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (205, 'Pudră Proteică 1kg', 150.00, 10);
INSERT INTO CROSSFIT_ADMIN.PRODUSE (PRODUSID, NUMEPRODUS, PRETCURENT, STOC) VALUES (206, 'Magneziu Praf', 25.00, 30);
