-- ==============================================================================
-- SCRIPT COMPLET DE RESETARE ȘI CREARE A BAZEI DE DATE (PROIECT CROSSFIT)
-- 1. Șterge tot (Tabele, View-uri, Secvențe) existente.
-- 2. Recreează structura corectă cu toate constrângerile.
-- ==============================================================================

-- ==============================================================================
-- 0. CLEANUP (ȘTERGERE OBIECTE VECHI)
-- Notă: Dacă primiți erori de tip "Table or View does not exist", ignorați-le.
-- Înseamnă că obiectul nu exista încă (prima rulare).
-- ==============================================================================

-- Ștergere View-uri
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_RAPORT_POPULARITATE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_MEMBRI_ABONAMENTE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_ANTRENORI_CONTACT';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Ștergere Tabele (cu CASCADE CONSTRAINTS pentru a rupe legăturile FK)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PARTICIPARI_COMPETITIE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORAR_TEMPLATE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NECESAR_ECHIPAMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MENTORAT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INSCRIERI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ACHIZITII CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLASE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEMBRI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMPETITII CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIPURI_ANTRENAMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ECHIPAMENTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUSE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ANTRENORI CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ABONAMENTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Ștergere Secvențe
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE MEMBRI_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ABONAMENTE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ANTRENORI_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CLASE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUSE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ECHIPAMENTE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE TIPURI_ANTRENAMENT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ACHIZITII_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ORAR_TEMPLATE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE COMPETITII_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ==============================================================================
-- 1. CREARE SECVENȚE
-- ==============================================================================
CREATE SEQUENCE MEMBRI_SEQ NOCACHE;
CREATE SEQUENCE ABONAMENTE_SEQ NOCACHE;
CREATE SEQUENCE ANTRENORI_SEQ NOCACHE;
CREATE SEQUENCE CLASE_SEQ NOCACHE;
CREATE SEQUENCE PRODUSE_SEQ NOCACHE;
CREATE SEQUENCE ECHIPAMENTE_SEQ NOCACHE;
CREATE SEQUENCE TIPURI_ANTRENAMENT_SEQ NOCACHE;
CREATE SEQUENCE ACHIZITII_SEQ NOCACHE;
CREATE SEQUENCE ORAR_TEMPLATE_SEQ NOCACHE;
CREATE SEQUENCE COMPETITII_SEQ NOCACHE;

-- ==============================================================================
-- 2. CREARE TABELE PRINCIPALE
-- ==============================================================================

-- Tabel: ABONAMENTE
CREATE TABLE ABONAMENTE (
    ABONAMENTID  NUMBER(10) PRIMARY KEY,
    TIPABONAMENT VARCHAR2(100) NOT NULL,
    PRET         NUMBER(10, 2) NOT NULL,
    -- Constrângere: Prețul nu poate fi negativ
    CONSTRAINT CHK_ABONAMENT_PRET CHECK (PRET >= 0)
);

-- Tabel: ANTRENORI
CREATE TABLE ANTRENORI (
    ANTRENORID   NUMBER(10) PRIMARY KEY,
    NUME         VARCHAR2(100) NOT NULL,
    PRENUME      VARCHAR2(100),
    SPECIALIZARE VARCHAR2(150),
    -- Constrângere: Doar specializări valide (Listă fixă)
    CONSTRAINT CHK_SPECIALIZARE CHECK (SPECIALIZARE IN ('Gimnastica', 'Haltere', 'Crossfit L1', 'Crossfit L2', 'Mobilitate', 'Cardio'))
);

-- Tabel: PRODUSE
CREATE TABLE PRODUSE (
    PRODUSID   NUMBER(10) PRIMARY KEY,
    NUMEPRODUS VARCHAR2(150) NOT NULL,
    PRETCURENT NUMBER(10, 2),
    STOC       NUMBER(5),
    -- Constrângeri: Preț și stoc pozitive
    CONSTRAINT CHK_PRODUS_PRET CHECK (PRETCURENT >= 0),
    CONSTRAINT CHK_PRODUS_STOC CHECK (STOC >= 0)
);

-- Tabel: ECHIPAMENTE
CREATE TABLE ECHIPAMENTE (
    ECHIPAMENTID    NUMBER(10) PRIMARY KEY,
    NUMEECHIPAMENT  VARCHAR2(100) NOT NULL,
    CANTITATETOTALA NUMBER(5),
    -- Constrângere: Cantitate pozitivă
    CONSTRAINT CHK_ECHIPAMENT_CANT CHECK (CANTITATETOTALA >= 0)
);

-- Tabel: TIPURI_ANTRENAMENT
CREATE TABLE TIPURI_ANTRENAMENT (
    TIPANTRENAMENTID NUMBER(10) PRIMARY KEY,
    NUMEWOD          VARCHAR2(100) NOT NULL,
    DESCRIERE        VARCHAR2(1000)
);

-- Tabel: COMPETITII
CREATE TABLE COMPETITII (
    COMPETITIEID NUMBER(10) PRIMARY KEY,
    NUME         VARCHAR2(150) NOT NULL,
    DATA         DATE NOT NULL,
    LOCATIE      VARCHAR2(150),
    TAXA         NUMBER(10, 2) DEFAULT 0,
    CONSTRAINT CHK_COMPETITIE_TAXA CHECK (TAXA >= 0)
);

-- ==============================================================================
-- 3. CREARE TABELE RELAȚIONALE (FK)
-- ==============================================================================

-- Tabel: MEMBRI
CREATE TABLE MEMBRI (
    MEMBRUID    NUMBER(10) PRIMARY KEY,
    NUME        VARCHAR2(100) NOT NULL,
    PRENUME     VARCHAR2(100),
    EMAIL       VARCHAR2(150) NOT NULL UNIQUE,
    ABONAMENTID NUMBER(10),
    -- Constrângere: Email valid (trebuie să conțină @)
    CONSTRAINT CHK_MEMBRU_EMAIL CHECK (EMAIL LIKE '%@%'),
    CONSTRAINT FK_MEMBRI_ABONAMENT FOREIGN KEY (ABONAMENTID) REFERENCES ABONAMENTE(ABONAMENTID)
);

-- Tabel: CLASE
CREATE TABLE CLASE (
    CLASAID          NUMBER(10) PRIMARY KEY,
    NUMEWOD          VARCHAR2(100) NOT NULL,
    DESCRIEREWOD     VARCHAR2(1000),
    DATAORA          TIMESTAMP(6),
    ANTRENORID       NUMBER(10),
    TIPANTRENAMENTID NUMBER(10),
    CONSTRAINT FK_CLASE_ANTRENOR FOREIGN KEY (ANTRENORID) REFERENCES ANTRENORI(ANTRENORID),
    CONSTRAINT FK_CLASE_TIP FOREIGN KEY (TIPANTRENAMENTID) REFERENCES TIPURI_ANTRENAMENT(TIPANTRENAMENTID)
);

-- Tabel: ACHIZITII (Membru cumpără Produs)
CREATE TABLE ACHIZITII (
    ACHIZITIEID    NUMBER(10) PRIMARY KEY,
    MEMBRUID       NUMBER(10),
    PRODUSID       NUMBER(10),
    DATAACHIZITIEI DATE DEFAULT SYSDATE,
    CANTITATE      NUMBER(3) DEFAULT 1,
    CONSTRAINT FK_ACHIZITII_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE,
    CONSTRAINT FK_ACHIZITII_PRODUS FOREIGN KEY (PRODUSID) REFERENCES PRODUSE(PRODUSID),
    CONSTRAINT CHK_ACHIZITIE_CANT CHECK (CANTITATE > 0)
);

-- Tabel: INSCRIERI (Membru se înscrie la Clasă)
CREATE TABLE INSCRIERI (
    MEMBRUID NUMBER(10) NOT NULL,
    CLASAID  NUMBER(10) NOT NULL,
    CONSTRAINT PK_INSCRIERI PRIMARY KEY (MEMBRUID, CLASAID),
    CONSTRAINT FK_INSCRIERI_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE,
    CONSTRAINT FK_INSCRIERI_CLASA FOREIGN KEY (CLASAID) REFERENCES CLASE(CLASAID) ON DELETE CASCADE
);

-- Tabel: MENTORAT (Antrenor mentorează Membru)
CREATE TABLE MENTORAT (
    ANTRENORID NUMBER(10) NOT NULL,
    MEMBRUID   NUMBER(10) NOT NULL,
    CONSTRAINT PK_MENTORAT PRIMARY KEY (ANTRENORID, MEMBRUID),
    CONSTRAINT FK_MENTORAT_ANTRENOR FOREIGN KEY (ANTRENORID) REFERENCES ANTRENORI(ANTRENORID),
    CONSTRAINT FK_MENTORAT_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE
);

-- Tabel: NECESAR_ECHIPAMENT (Tip Antrenament necesită Echipament)
CREATE TABLE NECESAR_ECHIPAMENT (
    TIPANTRENAMENTID NUMBER(10) NOT NULL,
    ECHIPAMENTID     NUMBER(10) NOT NULL,
    CONSTRAINT PK_NECESAR_ECHIPAMENT PRIMARY KEY (TIPANTRENAMENTID, ECHIPAMENTID),
    CONSTRAINT FK_NECESAR_TIP FOREIGN KEY (TIPANTRENAMENTID) REFERENCES TIPURI_ANTRENAMENT(TIPANTRENAMENTID) ON DELETE CASCADE,
    CONSTRAINT FK_NECESAR_ECHIPAMENT FOREIGN KEY (ECHIPAMENTID) REFERENCES ECHIPAMENTE(ECHIPAMENTID) ON DELETE CASCADE
);

-- Tabel: ORAR_TEMPLATE (Reguli pentru generarea automată a orarului)
CREATE TABLE ORAR_TEMPLATE (
    TEMPLATEID       NUMBER(10) PRIMARY KEY,
    ZIUASAPTAMANII   NUMBER(1) NOT NULL,
    ORA              VARCHAR2(5) NOT NULL,
    NUMEWOD_TEMPLATE VARCHAR2(100),
    ANTRENORID       NUMBER(10),
    TIPANTRENAMENTID NUMBER(10),
    CONSTRAINT CHK_ZIUA_SAPTAMANII CHECK (ZIUASAPTAMANII BETWEEN 1 AND 7),
    CONSTRAINT CHK_ORA_FORMAT CHECK (REGEXP_LIKE(ORA, '^[0-2][0-9]:[0-5][0-9]$')),
    CONSTRAINT FK_ORAR_ANTRENOR FOREIGN KEY (ANTRENORID) REFERENCES ANTRENORI(ANTRENORID) ON DELETE SET NULL,
    CONSTRAINT FK_ORAR_TIP FOREIGN KEY (TIPANTRENAMENTID) REFERENCES TIPURI_ANTRENAMENT(TIPANTRENAMENTID) ON DELETE SET NULL
);

-- Tabel: PARTICIPARI_COMPETITIE (Membru participă la Competiție)
CREATE TABLE PARTICIPARI_COMPETITIE (
    COMPETITIEID NUMBER(10) NOT NULL,
    MEMBRUID     NUMBER(10) NOT NULL,
    LOCULOBTINUT NUMBER(3) DEFAULT 0,
    CONSTRAINT PK_PARTICIPARI_COMP PRIMARY KEY (COMPETITIEID, MEMBRUID),
    CONSTRAINT FK_PART_COMP FOREIGN KEY (COMPETITIEID) REFERENCES COMPETITII(COMPETITIEID) ON DELETE CASCADE,
    CONSTRAINT FK_PART_MEMBRU FOREIGN KEY (MEMBRUID) REFERENCES MEMBRI(MEMBRUID) ON DELETE CASCADE
);


-- ==============================================================================
-- 4. CREARE VIZUALIZĂRI (VIEWS)
-- ==============================================================================

-- View Simplu: Date de contact antrenori
CREATE OR REPLACE VIEW V_ANTRENORI_CONTACT AS
SELECT AntrenorID, Nume, Prenume, Specializare
FROM ANTRENORI;

-- View Compus (pentru Update): Membri și Abonamentele lor
CREATE OR REPLACE VIEW V_MEMBRI_ABONAMENTE AS
SELECT m.Nume, m.Prenume, m.Email, a.TipAbonament, a.Pret
FROM MEMBRI m
JOIN ABONAMENTE a ON m.AbonamentID = a.AbonamentID;

-- View Complex (Group By + Having): Raport Popularitate
CREATE OR REPLACE VIEW V_RAPORT_POPULARITATE AS
SELECT a.TipAbonament, COUNT(m.MembruID) AS Numar_Membri
FROM ABONAMENTE a
JOIN MEMBRI m ON a.AbonamentID = m.AbonamentID
GROUP BY a.TipAbonament
HAVING COUNT(m.MembruID) > 2;

-- Finalizare
COMMIT;
